spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: haha
    sentinel:
      transport:
        dashboard: localhost:8099
  application:
    name: test-server-oauth
server:
  port: 10004
dubbo:
  registry:
    address: spring-cloud://localhost:8848
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: test-server-one
management:
  endpoints:
    web:
      exposure:
        include: '*'
