spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: haha
    sentinel:
      transport:
        dashboard: localhost:8099
  application:
    name: test-server-one
server:
  port: 10001
dubbo:
  scan:
    base-packages: com.gqx.cloud.serverone.dubbo
  registry:
    address: spring-cloud://localhost:8848
  protocol:
    name: dubbo
    port: -1
management:
  endpoints:
    web:
      exposure:
        include: '*'
knife4j:
  enable: true

cloud:
  gqx:
    multiple:
      datasource:
        maxActive: 123
        sources:
          -
            driverClassName: xxxx
            url: xxxxx
          -
            driverClassName: bbbbb
            url: bbbbb